TripGuide/Controllers/FavoriteController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TripGuide.Data.Repositories;
using TripGuide.Enums;
using TripGuide.Models;

namespace TripGuide.Controllers;

[Authorize]
public class FavoriteController : Controller
{
    private readonly FavoriteRepository _favoriteRepository;

    public FavoriteController(FavoriteRepository favoriteRepository)
    {
        _favoriteRepository = favoriteRepository;
    }

    [HttpGet]
    [Route("{action}")]
    public async Task<ActionResult<List<FavoriteViewModel>>> GetAllFavoritesByUserId()
    {
        var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;

        var favorites = await _favoriteRepository.GetAllFavoritesByUserIdAsync(user);

        var result = new List<FavoriteViewModel>();
        
        foreach (var favorite in favorites)
        {
            var favoriteViewModel = favorite.MapToViewModel();
            favoriteViewModel.FavoriteCount = await _favoriteRepository.CountTripFavoritesAsync(favorite.TripId);
            result.Add(favoriteViewModel);
        }
        return View(result);
    }

    [HttpPost]
    [Route("{action}/{tripId:int}/{source}")]
    public async Task<ActionResult> DeleteFavorite(int tripId, SourceEnum source)
    {
        var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
        await _favoriteRepository.DeleteFavoriteAsync(tripId, userId);

        switch (source)
        {
            case SourceEnum.TripList:
                return RedirectToAction("Index", "Home");
            case SourceEnum.TripDetails:
                return RedirectToAction("HomeTripDetails", "Home", new {id = tripId});
            case SourceEnum.FavoriteList:
                return RedirectToAction("GetAllFavoritesByUserId");
        }

        return RedirectToAction("Index", "Home");
    }

    [HttpPost]
    [Route("{action}/{tripId:int}/{source}")]
    public async Task<ActionResult> CreateFavorite(int tripId, string source)
    {
        var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;

        var isAlreadyFavoriteForUserAsync = await _favoriteRepository.IsAlreadyFavoriteForUserAsync(tripId, user);

        if (!isAlreadyFavoriteForUserAsync)
        {
            await _favoriteRepository.CreateFavoriteAsync(tripId, user);
        }

        if (source == SourceEnum.TripList.ToString())
        {
            return RedirectToAction("Index", "Home");
        }

        return RedirectToAction("HomeTripDetails", "Home", new {id = tripId});
    }
}

TripGuide/Controllers/HomeController.cs
using System.Diagnostics;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TripGuide.Data.Entities;
using TripGuide.Data.Repositories;
using TripGuide.Models;

namespace TripGuide.Controllers;

public class HomeController : Controller
{
    private readonly TripRepository _tripRepository;
    private readonly FavoriteRepository _favoriteRepository;

    public HomeController(TripRepository tripRepository, FavoriteRepository favoriteRepository)
    {
        _tripRepository = tripRepository;
        _favoriteRepository = favoriteRepository;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index(List<string> citiesToFilter, List<string> countriesToFilter)
    {
        var allTrips = await _tripRepository.GetAllPublicTrips(citiesToFilter, countriesToFilter);
        
        var result = new IndexViewModel();
        result.Trips = new List<IndexTripViewModel>();
        result.AllCitites = new List<SelectListItem>();
        result.AllCountries = new List<SelectListItem>();

        var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        List<Favorite> userFavorites = null;
        if (userId != null)
        {
            userFavorites = await _favoriteRepository.GetAllFavoritesByUserIdAsync(userId);
        }
        
        foreach (var trip in allTrips)
        {
            var indexTripViewModel = trip.MapToIndexTripViewModel();
            indexTripViewModel.IsCreatedByCurrentUser = trip.UserId == userId;
            indexTripViewModel.FavoriteCount = await _favoriteRepository.CountTripFavoritesAsync(trip.Id);
            if (userFavorites != null)
            {
                var favorite = userFavorites.SingleOrDefault(f => f.TripId == trip.Id);
                indexTripViewModel.IsAlreadyCurrentUserFavorite = favorite != null;
            }
            result.Trips.Add(indexTripViewModel);
        }

        var allCitites = await _tripRepository.GetAllTripCitiesAsync();
        foreach (var city in allCitites)
        {
            result.AllCitites.Add(new SelectListItem(city,city.ToLower()));
        }

        var allCountries = await _tripRepository.GetAllTripCountriesAsync();
        foreach (var country in allCountries)
        {
            result.AllCountries.Add(new SelectListItem(country, country.ToLower()));
        }
        
        var tripsSorted = result.Trips.OrderByDescending(f => f.FavoriteCount).ToList();
        result.Trips = tripsSorted;
        return View(result);
        
    }
    
    [HttpGet]
    public IActionResult Privacy()
    {
        return View();
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    [HttpGet]
    [Route("{id:int}")]
    public async Task<ActionResult> HomeTripDetails(int id)
    {
        var trip = await _tripRepository.GetTripByIdAsync(id);

        var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        List<Favorite> userFavorites = null;
        if (userId != null)
        {
            userFavorites = await _favoriteRepository.GetAllFavoritesByUserIdAsync(userId);
        }

        var indexViewModel = trip.MapToDetailsViewModel();
        indexViewModel.IsCreatedByCurrentUser = trip.UserId == userId;
        indexViewModel.FavoriteCount = await _favoriteRepository.CountTripFavoritesAsync(trip.Id);
        
        if (userFavorites != null)
        {
            var favorite = userFavorites.SingleOrDefault(f => f.TripId == trip.Id);
            indexViewModel.IsAlreadyCurrentUserFavorite = favorite != null;
        }
        
        return View(indexViewModel);
    }
}

TripGuide/Views/Home/HomeTripDetails.cshtml
@using Microsoft.AspNetCore.Identity
@using TripGuide.Enums
@model TripDetailsViewModel
@inject SignInManager<IdentityUser> SignInManager

<h1 class="display-1 text-center" >Trip details @Model.Name</h1>
<div class="container text-center">
    <div class="row">
        <p class="col fs-3">Location: @Model.City, @Model.Country</p>
        <p class="col fs-3">Loves: @Model.FavoriteCount</p>
        @if (SignInManager.IsSignedIn(User))
        {
            <div class="col">
                @if (!Model.IsCreatedByCurrentUser && !Model.IsAlreadyCurrentUserFavorite)
                {
                    <form asp-controller="Favorite" asp-action="CreateFavorite" method="post" asp-route-tripId="@Model.Id" asp-route-source="@SourceEnum.TripDetails.ToString()">
                        <button class="btn btn-outline-secondary" type="submit">
                            <i class="bi bi-heart"></i>
                        </button>
                    </form>
                }
                else
                {
                    <form asp-controller="Favorite" asp-action="DeleteFavorite" method="post" asp-route-tripId="@Model.Id" asp-route-source="@SourceEnum.TripDetails.ToString()">
                        <button class="btn btn-outline-secondary" type="submit">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ff0000" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                            </svg>
                        </button>
                    </form>
                }
            </div>
        }
    </div>
</div>
<div class="ms-auto me-auto" style="width: 800px; height: 600px;" id="map"></div>
<h2 class="display-2">Places to visit</h2>
<table class="table table-hover table-striped">
    <thead>
    <tr>
        <th scope="col">Order</th>
        <th scope="col">Name</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var placeToVisit in @Model.PlacesToVisit)
    {
        <tr>
            <td>@placeToVisit.VisitOrder</td>
            <td>@placeToVisit.Name</td>
        </tr>
    }
    </tbody>
</table>

@section Scripts
{
    <script type="text/javascript">
        async function main(){
            const cityToSearch = "@Model.City";
            const countryToSearch = "@Model.Country";
            
            const placesToVisit = @Html.Raw(Json.Serialize(Model.PlacesToVisit));
        
            const response = await fetch('https://nominatim.openstreetmap.org/search?city=' + cityToSearch + '&country=' + countryToSearch + '&format=json');
            const data = await response.json();
        
            const mapOptions = {
                center: [data[0].lat, data[0].lon],
                zoom: 11
            };
            
            const map = new L.map('map', mapOptions);
            const layer = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');
            map.addLayer(layer);   
            
            const latlngs = [];
            
            placesToVisit.forEach(placeToVisit => {
                const marker = L.marker([placeToVisit.latitude, placeToVisit.longitude]).addTo(map);
                marker.bindPopup(placeToVisit.visitOrder.toString() + " " + placeToVisit.name.toString());  
                latlngs.push([placeToVisit.latitude, placeToVisit.longitude]);
            });
            
            L.polyline(latlngs, {color: 'red'}).addTo(map);
            
        }
        
        main();
    </script>
}

TripGuide/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using TripGuide.Enums
@model IndexViewModel
@inject SignInManager<IdentityUser> SignInManager

@{
    ViewData["Title"] = "Trips List";
}

<h1 class="display-1">Trips List</h1>
<div class="container">
    <div class="row">
        <div class="col">
            <form class="d-grid gap-2" method="get">
                <label class="form-control mb-1" for="citiesToFilter">City</label>
                <select class="form-select mb-3" size="5" id="citiesToFilter" name="citiesToFilter" asp-items="@Model.AllCitites" multiple="multiple"></select>
                
                <label class="form-control mb-1" for="countriesToFilter">Country</label>
                <select class="form-select mb-3" size="5" id="countriesToFilter" name="countriesToFilter" asp-items="@Model.AllCountries" multiple="multiple"></select>
                
                <button class="btn btn-outline-primary" type="submit">Filter</button>
            </form>
        </div>
        <div class="col-10">
            <table class="table table-hover table-striped">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">City</th>
                    <th scope="col">Country</th>
                    <th scope="col">Loves</th>
                    <th scope="col">Favorite</th>
                </tr>
                </thead>

                <tbody>
                @foreach (var trip in Model.Trips)
                {
                    <tr>
                        <td>
                            <a asp-action="HomeTripDetails" asp-route-id="@trip.Id">
                                <span>@trip.Name</span>
                            </a>
                        </td>
                        <td>@trip.City</td>
                        <td>@trip.Country</td>
                        <td>@trip.FavoriteCount</td>
                        @if (SignInManager.IsSignedIn(User) && !trip.IsCreatedByCurrentUser)
                        {
                            @if (!trip.IsAlreadyCurrentUserFavorite)
                            {
                                <td>
                                    <form method="post" asp-controller="Favorite" asp-action="CreateFavorite" asp-route-tripId="@trip.Id" asp-route-source="@SourceEnum.TripList.ToString()">
                                        <button class="btn btn-outline-secondary" type="submit">
                                            <i class="bi bi-heart"></i>
                                        </button>
                                    </form>
                                </td>
                            }
                            else
                            {
                                <td>
                                    <form asp-controller="Favorite" asp-action="DeleteFavorite" asp-route-tripId="@trip.Id" asp-route-source="@SourceEnum.TripList.ToString()">
                                        <button class="btn btn-outline-secondary" type="submit">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ff0000" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                                            </svg>
                                        </button>
                                    </form>
                                </td>
                            }
                        }
                        else
                        {
                            <td></td>
                        }
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>